[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["eufracio <eufraciochavez327@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.109.2"
django = "^5.0.2"
black = "^24.1.1"
uvicorn = "^0.27.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
